version: '2'
services:
  openprojectdb:
    image: healthcheck/postgres
    environment:
      - POSTGRES_DB=openproject
      - POSTGRES_USER=openproject
      - POSTGRES_PASSWORD=openproject
    volumes:
      - opdb:/var/lib/openproject/postgresql/data
    networks: 
    - opnet

  openprojectcache:
    image: dockhero/memcached
    hostname: openprojectcache
    networks: 
      - opnet

  openprojectapp:
    image: openproject/community:7
    hostname: openprojectapp
    environment:
      - DATABASE_URL=postgres://openproject:openproject@openprojectdb:5432/openproject?pool=10&encoding=unicode&timeout=5000&reconnect=true
      - SECRET_KEY_BASE=ahfjakhlfajkdlhfljkhfkjahfkjfhkdjshf
      - CACHE_MEMCACHE_SERVER=openprojectcache
      - CACHE_NAMESPACE=openproject
    volumes:
      - opapp:/data/openprojectapp
    ports:
      - 8080:80
    depends_on:
      - "openprojectdb"
      - "openprojectcache"
    networks: 
      - opnet

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.0.1
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - opnet

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.0.1
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - opnet

  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - opnet
    depends_on:
      - elasticsearch
      - elasticsearch2
    volumes:
      - opapp:/data/openprojectapp

  kibana:
    build:
      context: kibana/
    image: docker.elastic.co/kibana/kibana-oss:6.0.1
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
    ports:
      - 5601:5601
    networks:
      - opnet

volumes:
  opapp:
    driver: local
  opdb:
    driver: local
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  opnet: